server:
  port: 8080

spring:
  application:
    name: manager-service
  datasource:
    url: jdbc:postgresql://localhost:5432/multi_module_app
    username: postgres
    password: postgres
  flyway:
    schemas:
      - user_management
    enabled: true
  jpa:
    show-sql: true
  security:
    oauth2:
         client:
           provider:
             keycloak:
               issuer-uri: http://localhost:8082/realms/multi-module-app
               user-name-attribute: preferred_username
           registration:
             keycloak:
               client-id: multi-module-app
               client-secret: NY6eZ2R1un8VOqxvMEQaRVNtBwAKYHoB
               scope:
                 - openid
                 - view_catalogue
                 - edit_catalogue
                 - microprofile-jwt


services:
  catalogue:
    uri: http://localhost:8081
    username: catalogue_service_user
    password: password