server:
  port: 8081

spring:
  security:
    user:
      name: catalogue_service_user
      password: '{noop}password'
      roles:
        - SERVICE
  application:
    name: catalogue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/multi_module_app
    username: postgres
    password: postgres
  flyway:
    schemas:
      - catalogue
    enabled: true
  jpa:
    show-sql: true
logging:
  level:
    sql: info